/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include <jni.h>
#include <stdlib.h>
#include <stdio.h>
#include <assert.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sqlite3.h>

#include "jnilogger.h"
/* Header for class com_daqi_sqlite_dbnative_SqlitedbForCK */

#ifndef _Included_com_daqi_sqlite_dbnative_SqlitedbForCK
#define _Included_com_daqi_sqlite_dbnative_SqlitedbForCK
#ifdef __cplusplus
extern "C" {
#endif


typedef int bool;
//define the bool values
#define true 1
#define false 0


/*
 * Class:     com_daqi_sqlite_dbnative_SqlitedbForCK
 * Method:    getDBVersion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_daqi_sqlite_dbnative_SqlitedbForCK_getDBVersion
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_daqi_sqlite_dbnative_SqlitedbForCK
 * Method:    readFileToDB
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_daqi_sqlite_dbnative_SqlitedbForCK_readFileToDB
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_daqi_sqlite_dbnative_SqlitedbForCK
 * Method:    dumpFileFromDB
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_daqi_sqlite_dbnative_SqlitedbForCK_dumpFileFromDB
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
